#! /home/josh/perl5.8.3/bin/perl

use strict;
use Cwd;
use File::Spec;

BEGIN {
  $^W = 1;  # Use warnings
  my $curdir = File::Spec->canonpath( Cwd::cwd() );
  unless ($curdir eq '/home/josh/src/B-Generate-1.07') {
    die ('This script must be run from /home/josh/src/B-Generate-1.07, not '."$curdir\n".
	 "Please re-run the Build.PL script here.\n");
  }
  @INC = 
    (
     '/home/josh/perl5.8.3/lib/5.8.3/i686-linux',
     '/home/josh/perl5.8.3/lib/5.8.3',
     '/home/josh/perl5.8.3/lib/site_perl/5.8.3/i686-linux',
     '/home/josh/perl5.8.3/lib/site_perl/5.8.3',
     '/home/josh/perl5.8.3/lib/site_perl',
     '/home/josh/src/B-Generate-1.07',
     '/home/josh/src/B-Generate-1.07/_build/lib'
    );
}

use My::Builder;

if (-e 'Build.PL' and not My::Builder->up_to_date("Build.PL", $0)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.
";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = My::Builder->resume (
  properties => {
    config_dir => '/home/josh/src/B-Generate-1.07/_build',
  },
);

$build->dispatch;
